language: cpp
compiler: gcc

before-install: sudo apt-get update
install: sudo apt-get install libev-dev libgoogle-glog-dev libgoogle-perftools-dev libjansson-dev libhiredis-dev libicu-dev libcurl4-openssl-dev libboost-dev
script: make all
