language: cpp
compiler: gcc

before-install: 
  - sudo apt-get update
  - wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz
  - tar xvzf glog-0.3.3.tar.gz

install: 
  - sudo apt-get install libev-dev libgoogle-perftools-dev libjansson-dev libhiredis-dev libicu-dev libcurl4-openssl-dev libboost-dev
  - cd glog-0.3.3
  - ./configure && make && make install
  
script: make all
